# Generated by Django 5.1.3 on 2024-11-11 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home', '0002_delete_test'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bookmarks',
            fields=[
                ('bookmark_id', models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'bookmarks',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('modelyear', models.IntegerField(primary_key=True, serialize=False)),
                ('make', models.CharField(max_length=30, unique=True)),
                ('model', models.CharField(max_length=100, unique=True)),
                ('vehicletype', models.CharField(blank=True, max_length=10, null=True)),
                ('drivetrain', models.CharField(blank=True, max_length=3, null=True)),
                ('curbweight', models.IntegerField(blank=True, null=True)),
                ('frontbarrierdriversr', models.IntegerField(blank=True, null=True)),
                ('frontbarrierpassengersr', models.IntegerField(blank=True, null=True)),
                ('sidebarrierrearseatsr', models.IntegerField(blank=True, null=True)),
                ('sidebarrierfrontseatsr', models.IntegerField(blank=True, null=True)),
                ('rolloverrisk', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'car',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('username', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('password', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'users',
                'managed': False,
            },
        ),
    ]
