# Generated by Django 5.1.3 on 2024-12-18 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_likes_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='likes',
            name='rolloverrisk',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=3, null=True),
        ),
    ]
